WhatsApp Business Chatbot

A lightweight, customizable WhatsApp chatbot designed for small and medium-sized businesses (SMBs) that need reliable, low-cost automated customer interaction. The system is powered by Large Language Models (LLMs) and is structured to allow switching between different models in future versions.

Overview

The chatbot integrates with the WhatsApp Business Cloud API to receive and respond to customer messages in real time. The architecture is modular, allowing the assistant’s behaviour, tone, and logic to be tailored to individual business needs.

Key Features

LLM-Powered Responses: Natural, context-aware replies generated by a language model.

Cost-Efficient for SMBs: Provides 24/7 automated support without the need for large support teams.

Customisable Logic: Supports personalised workflows, prompts, and business-specific conversation rules.

Real-Time WhatsApp Integration: Built on the WhatsApp Business Cloud API with webhook-based message handling.

Simple and Extendable Architecture: FastAPI backend designed for clarity and future extensibility.

How It Works

Customers send a message to the business’s WhatsApp number.

WhatsApp forwards the message to the webhook endpoint.

The backend processes the message and sends it to the LLM.

The model returns a generated reply.

The chatbot sends the response back through the WhatsApp Cloud API.

Tech Stack

Python 3

FastAPI (webhook server)

WhatsApp Business Cloud API

OpenAI LLMs

ngrok (local development tunnelling)

Status

This project is under active development and intended for future deployment to production environments.